- osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: right

- osx_defaults:
    domain: com.apple.mail
    key: ConversationViewSortDescending
    type: bool
    value: true

- osx_defaults:
    domain: com.apple.mail-shared
    key: DisableURLLoading
    type: bool
    value: true