- name: gcloud path in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"

- name: gcloud completion in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

- name: disable zsh compfix
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: ZSH_DISABLE_COMPFIX=true
    insertbefore: BOF

- name: Add direnv to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: eval "$(direnv hook zsh)"
