- name: gcloud path in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"

- name: gcloud completion in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: source "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"

- name: disable zsh compfix
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: ZSH_DISABLE_COMPFIX=true
    insertbefore: BOF

- name: Add direnv to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: eval "$(direnv hook zsh)"

- name: Add kube-ps1 to .zshrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      source "/usr/local/opt/kube-ps1/share/kube-ps1.sh"
      PROMPT='$(kube_ps1)'$PROMPT
      kubeoff

- name: Add rbenv to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: eval "$(rbenv init -)"

- name: Add nvm to .zshrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
      [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
